[WIP] Projectを階層化して管理できる機能
yusk/todoapp-django-sample pull request #2
Opened 2022-02-26 05:52 UTC by Reimei1213

## やったこと
- Projectモデルにchild_projectsカラムを追加
- ProjectテーブルとProjectテーブルをつなぐ中間テーブルを追加
- migrate用のファイルを生成
- child_projectsカラム追加に伴いchild_projectsを保存できる機能追加

## やること
- `python3 manage.py migrate`

2022-03-06 13:36 UTC, yusk requested changes
ほぼオッケーです、 更新処理の時の挙動の確認だけお願いします。

2022-03-06 13:36 UTC, yusk commented on main/serializers/project.py
update method がないので、更新の時に適切な処理がなされないと思われる

2022-03-06 22:15 UTC, Reimei1213 commented on main/serializers/project.py
ご確認ありがとうございます！

初歩的なミスですね、すみません。
create methodを実装して完全に満足してました...

2022-03-12 14:49 UTC, yusk approved these changes
動作確認できました！
LGTM 👍

2022-03-12 14:49 UTC, merged